//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookCollection
    {
        public long Id { get; set; }
        public long BookId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CollectionDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
