//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBorrow
    {
        public long Id { get; set; }
        public long BookId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public bool IsReturn { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> NeedReturnDate { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
    }
}
