//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookBorrow
    {
        public long Id { get; set; }
        public long BookId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public bool IsReturn { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> NeedReturnDate { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
        public virtual User User { get; set; }
    }
}
