//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookProjectEntities : DbContext
    {
        public BookProjectEntities()
            : base("name=BookProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookBorrow> BookBorrows { get; set; }
        public virtual DbSet<BookCategory> BookCategories { get; set; }
        public virtual DbSet<BookCollection> BookCollections { get; set; }
        public virtual DbSet<BookInfo> BookInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<V_BookBorrow> V_BookBorrow { get; set; }
        public virtual DbSet<V_BookCollection> V_BookCollection { get; set; }
    }
}
